[package]
name = "dobro"
version = "0.2.2"
authors = ["Daniel Rivas <ers.daniel+dev@gmail.com>"]

[dependencies]
ncurses = "5.84.0"

[dependencies.pandora]
path = "src/lib/pandora-rs"

[dependencies.ao]
path = "src/lib/ao-rs"

[dependencies.earwax]
path = "src/lib/earwax"
