[package]
name = "dobro"
version = "0.1.0"
authors = ["Daniel Rivas <ers.daniel+dev@gmail.com>"]

[dependencies]
rpassword = "0.3"
ncurses = "5.84.0"

[dependencies.pandora]
path = "src/pandora-rs"

[dependencies.ao]
path = "src/ao-rs"

[dependencies.earwax]
path = "src/earwax"
