[package]
name = "pandora"
version = "0.1.0"
authors = ["Daniel Rivas <ers.daniel+dev@gmail.com>"]

[dependencies]
hyper = "0.9.10"
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"

[[example]]
name = "main"
path = "examples/main/main.rs"
